// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDw-e_h7bNKpAXY9MP6p01DbpS264sNg84',
    appId: '1:471947615426:web:0fa5d41ebc708fdc67ef5b',
    messagingSenderId: '471947615426',
    projectId: 'store-search-b897f',
    authDomain: 'store-search-b897f.firebaseapp.com',
    databaseURL: 'https://store-search-b897f-default-rtdb.firebaseio.com',
    storageBucket: 'store-search-b897f.appspot.com',
    measurementId: 'G-5KET03E57F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs90p2P-35Zfwgd9wqMWkd8uAmjeBAOjQ',
    appId: '1:471947615426:android:1b819cb7309bcf7667ef5b',
    messagingSenderId: '471947615426',
    projectId: 'store-search-b897f',
    databaseURL: 'https://store-search-b897f-default-rtdb.firebaseio.com',
    storageBucket: 'store-search-b897f.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXf11RqGS9itlbLY3BslBvdNoZRVEcWvc',
    appId: '1:471947615426:web:4c56e2b9e21eb0b867ef5b',
    messagingSenderId: '471947615426',
    projectId: 'store-search-b897f',
    authDomain: 'store-search-b897f.firebaseapp.com',
    databaseURL: 'https://store-search-b897f-default-rtdb.firebaseio.com',
    storageBucket: 'store-search-b897f.appspot.com',
    measurementId: 'G-C3Y82YK5S6',
  );
}
